#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jun 24, 2019 03:01:25 PM IST  platform: Windows NT

import sys

from tkinter import filedialog as fd

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import test_ann_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    test_ann_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    test_ann_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


def getpath():
    file= fd.askopenfile()
    if file:
        print(file.name)
    
    
    
    
class Toplevel1:
    def getpath(self):
        file = fd.askopenfile()
        if file: 
            print(file.name)

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        font10 = "-family {Courier New} -size 10 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("930x883+650+150")
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.043, rely=0.011, relheight=0.909
                , relwidth=0.939)
        self.Canvas1.configure(background="#91fbff")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=873)

        self.Label1 = tk.Label(self.Canvas1)
        self.Label1.place(relx=0.344, rely=0.025, height=36, width=252)
        self.Label1.configure(activeforeground="#000000")
        self.Label1.configure(background="#d8d86e")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''ANNOTATION TOOL''')
        self.Label1.configure(width=252)

        self.Frame1 = tk.Frame(self.Canvas1)
        self.Frame1.place(relx=0.023, rely=0.237, relheight=0.492
                , relwidth=0.578)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=505)

        self.Label2 = tk.Label(self.Canvas1)
        self.Label2.place(relx=0.023, rely=0.125, height=26, width=112)
        self.Label2.configure(background="#7fb8d8")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''Path''')
        self.Label2.configure(width=112)

        self.Entry1 = tk.Entry(self.Canvas1)
        self.Entry1.place(relx=0.183, rely=0.125,height=24, relwidth=0.234)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font=font10)
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(insertbackground="black")

        self.Label3 = tk.Label(self.Canvas1)
        self.Label3.place(relx=0.023, rely=0.174, height=26, width=112)
        self.Label3.configure(background="#7bb3d8")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(text='''Set Threashold''')
        self.Label3.configure(width=112)

        self.Entry2 = tk.Entry(self.Canvas1)
        self.Entry2.place(relx=0.183, rely=0.174,height=24, relwidth=0.234)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font=font10)
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(insertbackground="black")

        self.Button1 = tk.Button(self.Canvas1)
        self.Button1.place(relx=0.756, rely=0.112, height=33, width=189)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d87338")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''ANNOTATE''')
        self.Button1.configure(width=189)

        self.Label4 = tk.Label(self.Canvas1)
        self.Label4.place(relx=0.756, rely=0.199, height=26, width=193)
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(text='''Enter Activity''')
        self.Label4.configure(width=193)

        self.Entry3 = tk.Entry(self.Canvas1)
        self.Entry3.place(relx=0.756, rely=0.237,height=24, relwidth=0.222)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font=font10)
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(width=194)

        self.Label5 = tk.Label(self.Canvas1)
        self.Label5.place(relx=0.756, rely=0.286, height=26, width=192)
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(text='''Current Activity''')
        self.Label5.configure(width=192)

        self.Text1 = tk.Text(self.Canvas1)
        self.Text1.place(relx=0.756, rely=0.324, relheight=0.042, relwidth=0.222)

        self.Text1.configure(background="white")
        self.Text1.configure(font=font9)
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(width=194)
        self.Text1.configure(wrap='word')

        self.Label6 = tk.Label(self.Canvas1)
        self.Label6.place(relx=0.756, rely=0.386, height=26, width=198)
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(text='''All Activities''')
        self.Label6.configure(width=198)

        self.Text2 = tk.Text(self.Canvas1)
        self.Text2.place(relx=0.756, rely=0.423, relheight=0.279, relwidth=0.222)

        self.Text2.configure(background="white")
        self.Text2.configure(font=font9)
        self.Text2.configure(foreground="black")
        self.Text2.configure(highlightbackground="#d9d9d9")
        self.Text2.configure(highlightcolor="black")
        self.Text2.configure(insertbackground="black")
        self.Text2.configure(selectbackground="#c4c4c4")
        self.Text2.configure(selectforeground="black")
        self.Text2.configure(width=194)
        self.Text2.configure(wrap='word')

        self.Button2 = tk.Button(self.Canvas1)
        self.Button2.place(relx=0.023, rely=0.909, height=33, width=67)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#bfd879")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Previous''')

        self.Button3 = tk.Button(self.Canvas1)
        self.Button3.place(relx=0.126, rely=0.909, height=33, width=43)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#c7d884")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Next''')

        self.Button4 = tk.Button(self.Canvas1)
        self.Button4.place(relx=0.332, rely=0.909, height=33, width=43)
        self.Button4.configure(activebackground="#ececec")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#c9d8a0")
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Start''')

        self.Button5 = tk.Button(self.Canvas1)
        self.Button5.place(relx=0.527, rely=0.909, height=33, width=43)
        self.Button5.configure(activebackground="#ececec")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#ced8a4")
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''Stop''')

        self.Button6 = tk.Button(self.Canvas1)
        self.Button6.place(relx=0.836, rely=0.909, height=53, width=111)
        self.Button6.configure(activebackground="#ececec")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#75a3d8")
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''E X I T''')
        self.Button6.configure(width=111)

        self.Label7 = tk.Label(self.Canvas1)
        self.Label7.place(relx=0.023, rely=0.822, height=36, width=157)
        self.Label7.configure(background="#5baed8")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(text='''Current Frame Number''')
        self.Label7.configure(width=157)

        self.Text3 = tk.Text(self.Canvas1)
        self.Text3.place(relx=0.218, rely=0.822, relheight=0.042, relwidth=0.096)

        self.Text3.configure(background="white")
        self.Text3.configure(font=font9)
        self.Text3.configure(foreground="black")
        self.Text3.configure(highlightbackground="#d9d9d9")
        self.Text3.configure(highlightcolor="black")
        self.Text3.configure(insertbackground="black")
        self.Text3.configure(selectbackground="#c4c4c4")
        self.Text3.configure(selectforeground="black")
        self.Text3.configure(width=84)
        self.Text3.configure(wrap='word')

        self.Button7 = tk.Button(self.Canvas1)
        self.Button7.place(relx=0.424, rely=0.909, height=33, width=51)
        self.Button7.configure(activebackground="#ececec")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#ccd89c")
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(text='''pause''')

        self.Button8 = tk.Button(self.Canvas1)
        self.Button8.place(relx=0.447, rely=0.125, height=23, width=36)
        self.Button8.configure(activebackground="#ececec")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0",command=self.getpath)
        self.Button8.configure(text='''. . .''')
        self.Button8.configure(width=36)

        self.Label8 = tk.Label(self.Canvas1)
        self.Label8.place(relx=0.023, rely=0.76, height=36, width=74)
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(text='''RANGE''')
        self.Label8.configure(width=74)

        self.Text4 = tk.Text(self.Canvas1)
        self.Text4.place(relx=0.126, rely=0.76, relheight=0.042, relwidth=0.05)
        self.Text4.configure(background="white")
        self.Text4.configure(font=font9)
        self.Text4.configure(foreground="black")
        self.Text4.configure(highlightbackground="#d9d9d9")
        self.Text4.configure(highlightcolor="black")
        self.Text4.configure(insertbackground="black")
        self.Text4.configure(selectbackground="#c4c4c4")
        self.Text4.configure(selectforeground="black")
        self.Text4.configure(width=44)
        self.Text4.configure(wrap='word')

        self.Label9 = tk.Label(self.Canvas1)
        self.Label9.place(relx=0.183, rely=0.76, height=36, width=12)
        self.Label9.configure(background="#d9d9d9")
        self.Label9.configure(disabledforeground="#a3a3a3")
        self.Label9.configure(foreground="#000000")
        self.Label9.configure(text='''-''')
        self.Label9.configure(width=12)

        self.Text5 = tk.Text(self.Canvas1)
        self.Text5.place(relx=0.206, rely=0.76, relheight=0.042, relwidth=0.05)
        self.Text5.configure(background="white")
        self.Text5.configure(font=font9)
        self.Text5.configure(foreground="black")
        self.Text5.configure(highlightbackground="#d9d9d9")
        self.Text5.configure(highlightcolor="black")
        self.Text5.configure(insertbackground="black")
        self.Text5.configure(selectbackground="#c4c4c4")
        self.Text5.configure(selectforeground="black")
        self.Text5.configure(width=44)
        self.Text5.configure(wrap='word')

    @staticmethod
    def popup1(event, *args, **kwargs):
        Popupmenu1 = tk.Menu(root, tearoff=0)
        Popupmenu1.configure(activebackground="#f9f9f9")
        Popupmenu1.configure(activeborderwidth="1")
        Popupmenu1.configure(activeforeground="black")
        Popupmenu1.configure(background="#d9d9d9")
        Popupmenu1.configure(borderwidth="1")
        Popupmenu1.configure(disabledforeground="#a3a3a3")
        Popupmenu1.configure(font="{Segoe UI} 9")
        Popupmenu1.configure(foreground="black")
        Popupmenu1.post(event.x_root, event.y_root)

if __name__ == '__main__':
    vp_start_gui()





